openapi: 3.0.1
info:
  title: API Auth Logout
  description: API untuk melakukan logout
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/auth/logout:
    post:
      summary: Logout dari aplikasi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Logout berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  status:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                        example: LogOut Success
