openapi: 3.0.1
info:
  title: API Items
  description: API  membuat item, mendapatkan data item, informasi kondisi stok, dll
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/items:
    post:
      summary: Membuat item baru
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Asus Rog G15 G513RM
                description:
                  type: string
                  example: Republik Of Gammer
                price:
                  type: number
                  example: 22000000
                quantity:
                  type: integer
                  example: 2
                category:
                  type: string
                  example: Elektronik
                supplier:
                  type: string
                  example: ROG
      responses:
        '201':
          description: Item berhasil dibuat
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 201
                  status:
                    type: string
                    example: Created
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                        example: success created new item

    get:
      summary: Mendapatkan daftar item
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Daftar item berhasil diambil
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  status:
                    type: string
                    example: OK
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 6
                        name:
                          type: string
                          example: Asus Rog G15 G513RM
                        description:
                          type: string
                          example: Republik Of Gammer
                        price:
                          type: number
                          example: 22000000
                        quantity:
                          type: integer
                          example: 2
                        category:
                          type: string
                          example: Elektronik
                        supplier:
                          type: string
                          example: ROG
                        created_by:
                          type: string
                          example: fatlem
                        created_at:
                          type: string
                          format: date-time
                          example: 2024-11-10T15:18:54.041Z
                        updated_at:
                          type: string
                          format: date-time
                          example: 2024-11-10T15:18:54.041Z

  /api/items/info:
    get:
      summary: Mendapatkan informasi detail stok item
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Informasi stok berhasil diambil
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  status:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      total_items:
                        type: integer
                        example: 1
                      total_stock_value:
                        type: number
                        example: 44000000
                      average_item_price:
                        type: number
                        example: 22000000
                      total_categories:
                        type: integer
                        example: 1
                      total_supplier:
                        type: integer
                        example: 1
                      updated_at:
                        type: string
                        format: date-time
                        example: 2024-11-10T15:19:28.1103773Z

  /api/items/condition:
    get:
      summary: Mendapatkan item berdasarkan kondisi stok
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: condition
          required: true
          schema:
            type: string
            enum: [under, over, equal]
            example: under
        - in: query
          name: threshold
          required: true
          schema:
            type: integer
            example: 4
      responses:
        '200':
          description: Daftar item berdasarkan kondisi stok
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  status:
                    type: string
                    example: OK
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 6
                        name:
                          type: string
                          example: Asus Rog G15 G513RM
                        description:
                          type: string
                          example: Republik Of Gammer
                        price:
                          type: number
                          example: 22000000
                        quantity:
                          type: integer
                          example: 2
                        category:
                          type: string
                          example: Elektronik
                        supplier:
                          type: string
                          example: ROG
                        created_by:
                          type: string
                          example: fatlem
                        created_at:
                          type: string
                          format: date-time
                          example: 2024-11-10T15:18:54.041Z
                        updated_at:
                          type: string
                          format: date-time
                          example: 2024-11-10T15:18:54.041Z

  /api/items/metric:
    get:
      summary: Mendapatkan metrik item
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Metrik item berhasil diambil
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  status:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      stock_status:
                        type: object
                        properties:
                          healthy_stock:
                            type: integer
                            example: 0
                          low_stock:
                            type: integer
                            example: 1
                          out_of_stock:
                            type: integer
                            example: 0
                      value_metrics:
                        type: object
                        properties:
                          highest_value_category:
                            type: string
                            example: Elektronik
                          lowest_value_category:
                            type: string
                            example: Elektronik
                          average_item_value:
                            type: number
                            example: 22000000
                          total_stock_value:
                            type: number
                            example: 44000000
                          total_items:
                            type: integer
                            example: 2
                      stock_distribution:
                        type: object
                        properties:
                          by_category:
                            type: object
                            additionalProperties:
                              type: string
                              example: "100.00%"
                          total_categories:
                            type: integer
                            example: 1
                          total_suppliers:
                            type: integer
                            example: 1

  /api/items/category:
    get:
      summary: Mendapatkan laporan item berdasarkan kategori
      parameters:
        - in: query
          name: category
          required: true
          schema:
            type: string
          description: Kategori item yang ingin dicari
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: Laporan item berdasarkan kategori berhasil diambil
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  status:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      ByCategory:
                        type: string
                        example: Electronic
                      Description:
                        type: string
                        example: electronic
                      TotalItem:
                        type: integer
                        example: 1
                      TotalQuantity:
                        type: integer
                        example: 3
                      TotalValue:
                        type: integer
                        example: 96000000
                      Items:
                        type: array
                        items:
                          type: object
                          properties:
                            Name:
                              type: string
                              example: RC48
                            Quantity:
                              type: integer
                              example: 3
                            SupplierID:
                              type: integer
                              example: 1
        '401':
          description: Unauthorized - Token tidak valid atau tidak ada
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 401
                  status:
                    type: string
                    example: Unauthorized
                  message:
                    type: string
                    example: "Token is missing or invalid"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
